"""empty message

Revision ID: 95404a8083a9
Revises: 25285d86475c
Create Date: 2020-04-04 18:58:23.073699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95404a8083a9'
down_revision = '25285d86475c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
